#!/usr/bin/env php
<?php

/**
 * Copyright (C) 2019  Tres Erres
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */
  
$args = $_SERVER['argv'];

require __DIR__.'/vendor/autoload.php';
include('helpers.php');

echo "\e[1;33m      ___           ___           ___           ___           ___     \n\e[0m";
echo "\e[1;33m     /  /\\         /  /\\         /  /\\         /  /\\         /  /\\    \n\e[0m";
echo "\e[1;33m    /  /::|       /  /::\\       /  /:/        /  /::\\       /  /::\\   \n\e[0m";
echo "\e[1;33m   /  /:|:|      /  /:/\\:\\     /  /:/        /  /:/\\:\\     /  /:/\\:\\  \n\e[0m";
echo "\e[1;33m  /  /:/|:|__   /  /::\\ \\:\\   /  /::\\____   /  /::\\ \\:\\   /  /::\\ \\:\\ \n\e[0m";
echo "\e[1;33m /__/:/_|::::\\ /__/:/\\:\\_\\:\\ /__/:/\\:::::\\ /__/:/\\:\\ \\:\\ /__/:/\\:\\_\\:\\\n\e[0m";
echo "\e[1;33m \\__\\/  /~~/:/ \\__\\/  \\:\\/:/ \\__\\/~|:|~~~~ \\  \\:\\ \\:\\_\\/ \\__\\/~|::\\/:/\n\e[0m";
echo "\e[1;33m       /  /:/       \\__\\::/     |  |:|      \\  \\:\\ \\:\\      |  |:|::/ \n\e[0m";
echo "\e[1;33m      /  /:/        /  /:/      |  |:|       \\  \\:\\_\\/      |  |:|\\/  \n\e[0m";
echo "\e[1;33m     /__/:/        /__/:/       |__|:|        \\  \\:\\        |__|:|~   \n\e[0m";
echo "\e[1;33m     \\__\\/         \\__\\/         \\__\\|         \\__\\/         \\__\\|    \n\n\e[0m";
echo "v1.0                                    Copyright (C) 2019  Tres Erres\n\n";
echo "This program comes with ABSOLUTELY NO WARRANTY.\n";
echo "This is free software, and you are welcome to redistribute it\n";
echo "under certain conditions; type `php maker copyright' for details.\n\n";

if (file_exists(__DIR__.'/bootstrap/app.php')) {
	$app = require_once __DIR__.'/bootstrap/app.php';
}

if (empty($args[1])) {
	$args[1] = "ayuda";
}

$funcion = 'cmd' . ucfirst(strtolower($args[1]));
if (!function_exists($funcion)) {
	die("\n\n\e[1;31mEl comando '" . $args[1] . "' no existe.\e[0m\n\nEscriba 'php maker help' para ver un listado de los comandos disponibles.\n\n");
}

$funcion(array_slice($args, 2));

echo "\n\n";

/************************************
 *	A PARTIR DE ACA VAN FUNCIONES
 ***********************************/

function cmdAyuda($args) {
	echo "Listado de comandos:\n";
	$filterFn = function($item) {
		return strpos($item, 'cmd') !== false;
	};
	$funciones = array_filter(get_defined_functions()['user'], $filterFn);
	foreach ($funciones as $funcion) {
		echo "\n· " . str_replace("cmd", "", $funcion);
	}
}

function cmdCopyright($args) {
	echo "https://github.com/tres-erres/slim-cli/blob/master/LICENSE";
}

function cmdNavegar($args) {
	echo navegar();
}

function cmdGenerar($args) {
	if (count($args) === 0) {
		$filterFn = function($item) {
			return substr($item, 0, 3) === 'gen';
		};
		$funciones = array_values(array_filter(get_defined_functions()['user'], $filterFn));
		if (count($funciones) > 0) {
			echo "Listado de generadores:\n";
			foreach ($funciones as $funcion) {
				echo "\n· " . str_replace("cmd", "", $funcion);
			}
			ask("Elección");
		} else {
			echo "No hay generadores.";
		}
		return;
	}
	switch ($args[0]) {
		case 'hojeador':
			include('generators/hojeador.php');
			break;
		case 'entidad':
			include('generators/entity.php');
			break;
		case 'form':
			include('generators/form.php');
			break;
		default:
			die("\e[1;31mNo existe el generador '" . $args[0] . "'.\e[0m\n\nEscriba 'php maker generar' para ver un listado de los generadores disponibles.\n\n");
			break;
	}
}
